config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :locations
  resources :posts
  resources :services

  root 'pages#home'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
	end
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
before_action :authenticate_admin!, only:[:new, :destroy, :edit]
	
	def index
		@services = Service.all
	end

	def show
		@service = Service.find(params[:id])
	end

	def new 
		@service = Service.new
	end

	def create
		@service = Service.new(service_params)
		@service.save
		redirect_to services_path
	end

	def edit 
		@service = Service.find(params[:id])
	end

	def update
		@service = Service.update(service_params)
	end

	def destroy 
		@service.find(param[:id])
		if @service.destroy!
			redirect_to services_path
		else
			redirect_to service_path
		end
	end

	private

	def service_params
		params.require(:service).permit(:name, :description)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand">Usa Electrical Systems</a>
    </div>
    
    <div class="navbar-container-right">
      
      <ul class="nav nav-pills navbar-right">
        <li>
          <%= link_to 'Home', root_path %>
        </li>
        <li>
          <%= link_to 'Services', services_path %>
        </li>
        <li>
          <%= link_to 'Locations', locations_path %>
        </li>
        <li>
          <%= link_to 'Blog', posts_path %>
        </li>
        <li>  
          <% if current_admin.present? %>
            <%= link_to 'Add Service', new_service_path %>
          <% end %>
        </li>
        <li>  
          <% if current_admin.present? %>
            <%= link_to 'Sign Out',destroy_admin_session_path, :method => :delete %>
          <% end %>
        </li>
      </ul>

    </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Usaelectricalsystemswebsite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<div class="container">
	<div class ="jumbotron">

		<h2>Greetings from USA Electrical Systems</h2>
		</br>
		<h3>We're Your Trusted Los Angeles Electrician!</h3>
		</br>
		<p>There’s a good chance you’re here because you have an electrical problem. Maybe you would like to make your home the envy of your neighbors by adding indoor or outdoor lighting. What about home theater equipment, a home automation system, or any of the TOP-OF-THE-LINE products we can supply and install for you?
		</br>
		</br>
		Whatever your needs are, we have a professional technician ready to make your home safer, more beautiful, more comfortable, and more valuable!
		</p>
	</div>


</div>

app/views/services/_form.html.erb
<div class="newtool-container">
  <div class="newtool-box">
    <%= form_for @service do |f| %>
      <div class="form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name, class:'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :description %><br>
        <%= f.text_area :description, :maxlength => 430, :rows => 5, class:'form-control', id:'description' %>
      </div>
      </br>
      <div class="actions">
        <%= f.submit class:"btn btn-default" %>
      </div>
    <% end %>
  </div>
</div>

app/views/services/edit.html.erb
this is edit

<% render 'form' %>

app/views/services/index.html.erb
<div class="container">

	<h2>Our Services</h2>
	</br>
	<h3>We Are The Residential Electrical Repair Experts for Los Angeles!</h3>
	</br>
	<p>Have you got an electrical issue? Need a new lighting fixture or ceiling fan installed? Maybe you need an outlet moved or replaced. Maybe you need a new outlet install - for that new flat panel television. When you choose Powell Electric, you're choosing a Los Angeles electrician with over 30 years experience in residential electric service, repair and installation.
	</p>
	</br>
	<h3>All Things Electrical</h3>
	<p>No matter the electrical need in your home or office, Powell Electric is the Los Angeles electrician to call! We specialize in residential electric repair. Our technicians are skilled and trained to meet your residential electrical needs.
	</p>
	</br>
	</br>
	<h3>Here are the residential electrical services we provide:</h3>
		<% @services.each do |service| %>
			<ul class="list-group">
				<%= link_to "#{service.name}", service_path(service), class: "list-group-item" %>
			</ul>
		<% end %>
</br>
</div>

app/views/services/new.html.erb
<div class="container service-new-container">

	<%= render 'form' %>

</div>

app/views/services/show.html.erb
<div class="container service-show-container">

	<h2><%= @service.name %></h2></br>
	<%= @service.description %>
	</br>
	</br>
	</br>
	</br>
	<p>Call USA Electrical Systems, your Los Angeles electrician, today to schedule a appointment to have the new appliance, hot tub, sauna, or pool pump hooked up.
	</p>
	</br>
 	<h2>Call Now! 800-000-0000</h2>
</div>